### ISSUE TITLE
-r false does not work

### ISSUE THREAD

**Issue by hajoeichler** [svenmueller/nube#6]
```
nube --profile my-profile servers instance create foobar -f '2 GB Performance' -d example.com -r false -w -p cloud-config.yaml
```

This results in firing up 2 nodes one called false-*.<region>.example.com.

So, region is still in and the name is `false`.

**Comment by svenmueller** [comment]
The syntax for using flags is the following:
- `--myflag=value`
- `--myflag="value with spaces"`

Your example should look like this:

```
nube --profile staging servers instance create foobar\
 -f="2 GB Performance"\
 -d=example.com\
 -p=cloud-config.yaml
```

Hint:
- `-r=false` can be skipped since `false` is now the default value.
- `-w=true`  can be skipped since `true` is now the default value.

**Comment by svenmueller** [comment]
To add the region manually add

```
--domain="region.domain.com"
```

**Comment by hajoeichler** [comment]
thx for the explanation
