### ISSUE TITLE
eu instead of lon

### ISSUE THREAD

**Issue by hajoeichler** [svenmueller/nube#7]
Let's use proper regions ;)

**Comment by svenmueller** [comment]
@hajoeichler Simply add the region yourself using the flag `--domain`. The rackspace internal region string will not be added anymore by default.

Example:

```
nube --profile staging servers instance create mywebserver\
 --flavor="1GB Standard Instance"\
 --image="Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)"\
 --user-data-file=/path/to/cloud-config.yaml\
 --domain=region.domain.com\
 --add-region=false
```

Hint: `--add-region=false` can be skipped since `false` is the default now.
